### ISSUE TITLE
Notification email after enter a new participation or comment.

### ISSUE THREAD

**Issue by jgrocha** [jgrocha/geopublic#19]
Users should be able to receive a notification after submitting a new participation or comment.

New notification options should be available on the profile.

Eventually, notifications should also be sent if someone else comments on the same participation.

**Comment by jgrocha** [comment]
This is partially fixed. Emails are sent when submitting new participations.

**Comment by AlmeidaSM** [comment]
Olá,
Estive a testar o recepção dos email's de notificação. 
Se criarmos uma participação recebe-se um email vindo de miguel.tavares@cm-agueda.pt. Porém, no spam. 
Se fizermos um comentário a uma participação (criada por mim ou não) não se recebe notificação por email. 
É suposto assim ser, uma vez que no seu comentário anterior diz "Emails are sent when submitting new participations."?

**Comment by jgrocha** [comment]
Estão a faltar os emails quando se acrescentam comentários. Só estão a sair os emails quando se insere uma nova participação. Tem que ser corrigido. Por isso ainda não fechei este *issue*.

**Comment by AlmeidaSM** [comment]
Ok, Obrigada.

Em 10 de fevereiro de 2015 16:01, Jorge Gustavo Rocha <
notifications@github.com> escreveu:

> Estão a faltar os emails quando se acrescentam comentários. Só estão a
> sair os emails quando se insere uma nova participação. Tem que ser
> corrigido. Por isso ainda não fechei este *issue*.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jgrocha/geopublic/issues/19#issuecomment-73725315>.
>



-- 
Sílvia Almeida
Contacto: 915135688
Email: sefa.b19@gmail.com
